# ?? ?? ??. ?? ??? ???? ? ?? ??? ?? ?????.
# ?? ??? ?? Packages ????? ?????.
commonVersion=0.0.9

# ????? ??
querydslVersion=7.6
springdocVersion=3.1.0

# AWS SDK for Java v2
# BOM ?? ????? ?? ?????? ??? ?? ??
# SDK ?? ???? ?? ???? ??? BOM ? ??? ?? ?
awsSdkVersion=2.34.5

# ???? ???? ?????
# spring-boot-testcontainers ? ??? ???? ?? ??? ?? ?
# ???? ??? ??? ?? ???? ??
# ??? ./gradlew dependencies --configuration testCompileClasspath ? ?
testcontainersVersion=2.0.5

# ?? ??
org.gradle.caching=true
org.gradle.parallel=true
